definitions:
  auth.SignUp.accountExists:
    properties:
      email:
        type: string
    type: object
  auth.SignUp.ok:
    properties:
      account:
        $ref: '#/definitions/views.AccountView'
    type: object
  auth.SignUp.request:
    properties:
      display_name:
        maxLength: 256
        minLength: 1
        type: string
      email:
        type: string
      password:
        maxLength: 32
        minLength: 8
        type: string
    required:
    - email
    - password
    type: object
  healthcheck.Healthcheck.view:
    properties:
      app_build:
        type: string
      app_name:
        type: string
      app_stage:
        type: string
    type: object
  views.AccountView:
    properties:
      created_at:
        type: integer
      display_name:
        type: string
      email:
        type: string
      id:
        type: string
      touched_at:
        type: integer
      updated_at:
        type: integer
    type: object
  views.ErrorView-auth_SignUp_accountExists:
    properties:
      msg:
        type: string
      payload:
        $ref: '#/definitions/auth.SignUp.accountExists'
      type:
        type: string
    required:
    - type
    type: object
info:
  contact: {}
paths:
  /auth/sign-up:
    post:
      consumes:
      - application/json
      description: Register a new account
      parameters:
      - description: Request body
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/auth.SignUp.request'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/auth.SignUp.ok'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/views.ErrorView-auth_SignUp_accountExists'
      summary: Sign up
      tags:
      - Authentication
  /healthcheck:
    get:
      consumes:
      - application/json
      description: Checks if the application is healthy
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/healthcheck.Healthcheck.view'
      summary: Healthcheck
      tags:
      - Utility
  /ping:
    get:
      consumes:
      - application/json
      description: Ping
      produces:
      - application/json
      responses:
        "200":
          description: pong
          schema:
            type: string
      summary: Ping
      tags:
      - Utility
swagger: "2.0"
