definitions:
  healthcheck.healthcheck.view:
    properties:
      app_build:
        type: string
      app_name:
        type: string
      app_stage:
        type: string
    type: object
info:
  contact: {}
paths:
  /healthcheck:
    get:
      consumes:
      - application/json
      description: Checks if the application is healthy
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/healthcheck.healthcheck.view'
      summary: Healthcheck
      tags:
      - Utility
  /ping:
    get:
      consumes:
      - application/json
      description: Ping
      produces:
      - application/json
      responses:
        "200":
          description: pong
          schema:
            type: string
      summary: Ping
      tags:
      - Utility
swagger: "2.0"
